"""empty message

Revision ID: 76ea142a15a9
Revises: 
Create Date: 2020-11-16 12:47:54.558364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76ea142a15a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('idMail', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('surname', sa.String(length=30), nullable=False),
    sa.Column('birthDate', sa.Date(), nullable=True),
    sa.Column('password', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('idMail')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('idMail', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('surname', sa.String(length=30), nullable=False),
    sa.Column('birthDate', sa.Date(), nullable=True),
    sa.Column('password', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('idMail')
    )
    op.create_table('coupon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endValidation', sa.Date(), nullable=False),
    sa.Column('idUser', sa.String(length=30), nullable=False),
    sa.Column('idCategory', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idCategory'], ['category.id'], ),
    sa.ForeignKeyConstraint(['idUser'], ['user.idMail'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('idCategory', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idCategory'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userbuyproduct',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idUser', sa.String(length=30), nullable=False),
    sa.Column('idProduct', sa.Integer(), nullable=False),
    sa.Column('numOfProd', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idProduct'], ['product.id'], ),
    sa.ForeignKeyConstraint(['idUser'], ['user.idMail'], ),
    sa.PrimaryKeyConstraint('id', 'idUser', 'idProduct')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userbuyproduct')
    op.drop_table('product')
    op.drop_table('coupon')
    op.drop_table('user')
    op.drop_table('category')
    op.drop_table('admin')
    # ### end Alembic commands ###
