"""empty message

Revision ID: 8532569330e8
Revises: 
Create Date: 2020-11-16 16:42:25.447917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8532569330e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('idmail', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('surname', sa.String(length=30), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('password', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('idmail')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('idmail', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('surname', sa.String(length=30), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('password', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('idmail')
    )
    op.create_table('coupon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endvalidation', sa.Date(), nullable=False),
    sa.Column('iduser', sa.String(length=30), nullable=False),
    sa.Column('idcategory', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idcategory'], ['category.id'], ),
    sa.ForeignKeyConstraint(['iduser'], ['users.idmail'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('idcategory', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idcategory'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userbuyproduct',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iduser', sa.String(length=30), nullable=False),
    sa.Column('idproduct', sa.Integer(), nullable=False),
    sa.Column('numofprod', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idproduct'], ['product.id'], ),
    sa.ForeignKeyConstraint(['iduser'], ['users.idmail'], ),
    sa.PrimaryKeyConstraint('id', 'iduser', 'idproduct')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userbuyproduct')
    op.drop_table('product')
    op.drop_table('coupon')
    op.drop_table('users')
    op.drop_table('category')
    op.drop_table('admin')
    # ### end Alembic commands ###
